version: '3.8'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  dbprod:
    image: mongo
    ports:
      - 30000:27017
    volumes:
      - v_dbproducts:/data/db
  dborder:
    image: mongo
    ports:
      - 30001:27017
    volumes:
      - v_dborders:/data/db
  order-api:
    build: ./order-service
    ports:
      - 3001:3000
    depends_on:
      - dborder
      - rabbit
  product-api:
    build: ./product-service
    ports:
      - 3000:3000
    depends_on:
      - rabbit
      - dbprod
volumes:
  v_dbproducts:
  v_dborders:

